Repository CMU-313/fall-2021-hw2-shrimp-gang, pull requests merged in 2021-09, with the labels that each got.

#12 Sidebar link
  mayan/apps/dashboard/apps.py
  mayan/apps/dashboard/links.py
  mayan/apps/dashboard/urls.py
  mayan/apps/dashboard/views.py
Labels: enhancement, good first issue

#13 Add link to url for dashboard.
  mayan/apps/dashboard/links.py
  mayan/apps/dashboard/urls.py
Labels: enhancement

#16 Creating model for applicant and reviewer
  mayan/apps/dashboard/models.py
Labels: documentation

#24 Instruction on testing
  README.md
  mayan/apps/testing/tests/test_instruction.txt
Labels: documentation

#26 Create README.MD for dashboard
  mayan/apps/dashboard/README.MD
Labels: documentation

#20 Making the model more easy to read
  mayan/apps/dashboard/models.py
Labels: documentation
